import re, html
def strip(t): return html.unescape(re.sub(r'<[^>]+>', '', t or '')).strip()
raw = open('/tmp/scmp92.xml', encoding='utf-8', errors='replace').read()
items = re.findall(r'<item>(.*?)</item>', raw, re.S)
print('SCMP items:', len(items))
for it in items[:40]:
    t = re.search(r'<title[^>]*>(.*?)</title>', it, re.S)
    l = re.search(r'<link>(.*?)</link>', it, re.S)
    d = re.search(r'<pubDate>(.*?)</pubDate>', it, re.S)
    print('  ', strip(d.group(1)) if d else '?', '|', strip(t.group(1))[:100] if t else '?')
    print('     ', strip(l.group(1)) if l else '?')
print()
print('===== NFRA shell =====')
nf = open('/tmp/nfra_list.html', encoding='utf-8', errors='replace').read()
print(nf[:2000])
